[server]
addr = "127.0.0.1:22122"
run_mode = "debug"
read_timeout = 60
write_timeout = 60
config_path = "./conf"
max_body_bytes = 1048576
cancel_timeout = 1


[jackcfg]
filename="/data0/applogs/query-log/query-log.log"
maxsize=500
maxage=7
maxbackups=1000
localtime=true
compress=false

[zapcfgs]
[zapcfgs.1]
level="info"
isdev=true
logmod=3
servername="query-log"

[app]
test=123

[log]
test=123

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
pswd = "123456"
db = "log"
charset="utf8"
locale = "Asia/Shanghai"
conn_lifetime = 5
max_open_conns = 5
max_idle_conns = 2


[redis_common]
host="127.0.0.1"
port=6379
connect_timeout = 1
read_timeout = 500
write_timeout = 500
max_idle = 2
max_active = 20
idle_timeout = 500