[server]
addr = "127.0.0.1:22122"
run_mode = "debug"
read_timeout = 60
write_timeout = 60
config_path = "./conf"
max_body_bytes = 1048576
cancel_timeout = 3

[app]
test=123

[log]
test=123

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
pswd = "123456"
db = "log"
charset="utf8"
locale = "Asia/Shanghai"
conn_lifetime = 5
max_open_conns = 5
max_idle_conns = 2
